name: Build and Test Image to Account

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches-ignore:
      - dependabot/*
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true

      - name: Install Dependencies
        run: npm ci

      - name: Generating coverage
        run: npm run test:cov

      - name: Generating coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          skip-step: install

      - name: Running the build
        run: |
          npm run build
